Repository ILYDSM/ILY-FE, pull requests merged in 2023-11, with the labels that each got.

#4 CardList 컴포넌트
  package.json
  src/components/common/CardList.tsx
Labels: FE, UI

#8 버튼 컴포넌트 수정
  App.tsx
  src/components/common/CustomButton.tsx
  src/components/common/TabBar.tsx
  src/styles/platte.ts
Labels: FE, feat

#12 CustomButton flex:1 구문 수정
  src/components/common/CustomButton.tsx
Labels: bug, FE

#11 모달 컴포넌트
  package.json
  src/components/common/CustomModal.tsx
  yarn.lock
Labels: FE, UI

#13 모임 카드 & 제목 바 & 만다라트
  src/components/common/MandalArt.tsx
  src/components/common/MeetCard.tsx
  src/components/common/TitleBar.tsx
Labels: FE, UI

#14 Feature/9 login
  .gitignore
  App.tsx
  app.json
  assets/login/google.png
  assets/login/kakao.png
  assets/login/naver.png
  package.json
  src/apis/axios.ts
  src/apis/bookmark/.gitkeep
  src/apis/buy/.gitkeep
  src/apis/mandalart/.gitkeep
  src/apis/meet/.gitkeep
  src/apis/user/index.ts
  src/apis/user/types.ts
  src/components/AuthButtons/GoogleButton.tsx
  src/components/AuthButtons/KakaoButton.tsx
  src/components/AuthButtons/NaverButton.tsx
  src/components/common/CustomButton.tsx
  src/components/common/CustomInput.tsx
  src/components/common/TitleBar.tsx
  src/navigations/Auth.tsx
  src/navigations/Main.tsx
  src/navigations/RootNavigation.tsx
  src/screens/ChangePwd.tsx
  src/screens/KakaoLogin.tsx
  src/screens/Login.tsx
  src/screens/NaverLogin.tsx
  src/screens/Rending.tsx
  src/screens/SignUp.tsx
  src/utils/AsyncStorage.ts
  src/utils/RootStackParam.ts
  yarn.lock
Labels: FE, feat

#17 Feature/15 group publishing
  src/components/PageTitle.tsx
  src/components/common/Category.tsx
  src/components/common/CustomSwitch.tsx
  src/components/common/MeetCard.tsx
  src/constants/mock.ts
  src/navigations/Group.tsx
  src/navigations/Main.tsx
  src/navigations/RootNavigation.tsx
  src/screens/CreateGroup.tsx
  src/screens/Group.tsx
  src/screens/GroupCategory.tsx
  src/screens/SearchResult.tsx
  src/utils/RootStackParam.ts
Labels: FE, feat

#23 Feature/22 sign up publishing
  src/navigations/Auth.tsx
  src/screens/ConfirmSignUp.tsx
  src/screens/SelectInterest.tsx
  src/screens/SignUp.tsx
  src/utils/RootStackParam.ts
Labels: FE, feat

#24 메뉴 페이지 퍼블리싱
  src/components/common/CardList.tsx
  src/navigations/Menu.tsx
  src/navigations/RootNavigation.tsx
  src/screens/GoalCalendar.tsx
  src/screens/MandalArtTheme.tsx
  src/screens/Menu.tsx
  src/utils/RootStackParam.ts
Labels: FE, feat

#26 feat: 목표 페이지 첫화면 퍼블리싱
  src/components/GoalCard.tsx
  src/screens/Goal.tsx
Labels: FE, feat

#28 메뉴 페이지 관련 작업
  src/components/common/GoalCheck.tsx
  src/components/common/TitleBar.tsx
  src/navigations/Menu.tsx
  src/screens/DeleteAccount .tsx
  src/screens/Menu.tsx
  src/screens/MenuChangePwd.tsx
  src/utils/RootStackParam.ts
Labels: FE, feat

#29 만다라트 테마
  src/components/common/MandalArt.tsx
  src/components/common/MandalArt/MandalArt.tsx
  src/components/common/MandalArt/MandalArtItem.tsx
  src/components/common/MandalArt/theme.ts
  src/navigations/RootNavigation.tsx
  src/types/MandalaArtThemeType.ts
Labels: refactor, FE, UI

#31 Feature/30 home publishing
  src/components/GoalCard.tsx
  src/components/ViewAll.tsx
  src/screens/Goal.tsx
  src/screens/Home.tsx
Labels: FE, feat

#34 목표 달성 페이지 퍼블리싱
  src/navigations/RootNavigation.tsx
  src/screens/GoalCalendar.tsx
Labels: FE, feat

#35 목표 상세 페이지 퍼블리싱(데모)
  src/components/GoalCard.tsx
  src/components/common/MandalArt/MandalArtItem.tsx
  src/navigations/Goal.tsx
  src/navigations/RootNavigation.tsx
  src/screens/Goal.tsx
  src/screens/GoalDetail.tsx
  src/screens/Home.tsx
  src/utils/RootStackParam.ts
Labels: FE, feat

#36 keyboard refactoring
  src/screens/ChangePwd.tsx
  src/screens/CreateGroup.tsx
  src/screens/Group.tsx
  src/screens/Login.tsx
  src/screens/NewPassword.tsx
  src/screens/SearchResult.tsx
  src/screens/SignUp.tsx
  src/screens/VerifyEmail.tsx
Labels: bug, FE

#39 로그인 회원가입 api 연동
  src/apis/axios.ts
  src/apis/user/index.ts
  src/apis/user/types.ts
  src/screens/DeleteAccount .tsx
  src/screens/Login.tsx
  src/screens/Menu.tsx
  src/screens/MenuChangePwd.tsx
  src/screens/SelectInterest.tsx
  src/screens/SignUp.tsx
  src/types/InterestType.ts
  src/utils/Rules.ts
  src/utils/Translates.ts
Labels: FE, feat

#43 Android 네비게이션 바 색상 핸들링
  App.tsx
  package.json
  src/components/common/CustomModal.tsx
  yarn.lock
Labels: FE, UI, feat

#45 목표 생성 퍼블리싱
  src/components/GoalCard.tsx
  src/components/common/MandalArt/MandalArt.tsx
  src/components/common/MandalArt/MandalArtEdit.tsx
  src/components/common/MandalArt/MandalArtThemeCard.tsx
  src/components/common/MandalArt/TouchableMandalArt.tsx
  src/components/common/MandalArt/TouchableMandalaArtItem.tsx
  src/components/common/MandalArt/theme.ts
  src/navigations/Goal.tsx
  src/screens/Goal.tsx
  src/screens/GoalCreateDetail.tsx
  src/screens/GoalCreateMain.tsx
  src/screens/GoalCreateResult.tsx
  src/screens/GoalCreateSub.tsx
  src/screens/GoalCreateTheme.tsx
  src/screens/GoalDetail.tsx
  src/screens/Home.tsx
  src/types/MandalaArtThemeType.ts
  src/utils/RootStackParam.ts
  src/utils/ThemeSelector.ts
Labels: FE, feat

#47 Feature/42 group api
  src/components/GoalCard.tsx
  src/components/common/Category.tsx
  src/components/common/CustomModal.tsx
  src/components/common/CustomSwitch.tsx
  src/screens/CreateGroup.tsx
  src/screens/GoalDetail.tsx
  src/screens/Group.tsx
  src/screens/GroupCategory.tsx
  src/screens/Home.tsx
  src/screens/Login.tsx
  src/screens/SearchResult.tsx
  src/screens/SelectInterest.tsx
  src/screens/SignUp.tsx
  src/utils/RootStackParam.ts
  src/utils/Rules.ts
Labels: FE, feat

#50 참가 신청 목록 수정
  src/components/common/CustomButton.tsx
  src/navigations/Goal.tsx
  src/screens/GoalJoinRequest.tsx
Labels: FE, UI, feat

#51 메뉴 페이지 연동
  src/apis/graph/index.ts
  src/apis/graph/types.ts
  src/apis/user/index.ts
  src/apis/user/types.ts
  src/components/common/GoalCheck.tsx
  src/components/common/MandalArt/MandalArtThemeCard.tsx
  src/navigations/Menu.tsx
  src/screens/GoalCalendar.tsx
  src/screens/InterestChange.tsx
  src/screens/MandalArtTheme.tsx
  src/screens/Menu.tsx
  src/screens/MenuChangePwd.tsx
  src/utils/RootStackParam.ts
Labels: FE, feat
